version: 2
updates:
  - package-ecosystem: cargo
    directories:
      - /
    schedule:
      interval: weekly
    labels:
      - C-Dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - C-Dependencies
