# The URL the site will be built for
base_url = "https://bevy.org"

# Used for the Atom feed
title = "Bevy Engine"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# When set to "true", the generated HTML files are minified.
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feeds = true
feed_limit = 1000

taxonomies = [{ name = "news", feed = true }]

[markdown.highlighting]

theme = "bevy-syntax-theme"

extra_themes = ["themes/bevy-syntax-theme.json"]
extra_grammars = ["grammars/ron.json"]

# error_on_missing_language = true

[extra]
# Put all your custom variables here
