# The URL the site will be built for
base_url = "https://bevy.org"

# Used for the Atom feed
title = "Bevy Engine"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# When set to "true", the generated HTML files are minified.
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feeds = true
feed_limit = 1000

taxonomies = [{ name = "news", feed = true }]

[markdown.highlighting]
style = "class"
# "github-dark" is not actually used by bevy. The field is required to be set
# and in the future bevy's custom CSS syntax theming will need to be defined 
# as a vscode theme
# https://github.com/getzola/zola/issues/3075#issuecomment-4189396022
theme = "github-dark"

# Load extra syntaxes (e.g. WGSL) for syntax highlighting
extra_grammars = ["syntaxes/ron.json"]

[extra]
# Put all your custom variables here
