rm ./content/news/2020-08-10-introducing-bevy/ecs_build-inverted.svg
rm ./content/news/2020-08-10-introducing-bevy/ecs_iter-inverted.svg
rm ./content/news/2020-08-19-scaling-bevy/balance-scale-inverted.svg
rm ./content/news/2020-09-19-bevy-0.2/bevy_tasks_1-inverted.svg
rm ./content/news/2020-09-19-bevy-0.2/bevy_tasks_2-inverted.svg
rm ./content/news/2020-09-19-bevy-0.2/get_component-inverted.svg
rm ./content/news/2020-11-03-bevy-0.3/ecs_add_remove-inverted.svg
rm ./content/news/2020-11-03-bevy-0.3/ecs_frag_iter-inverted.svg
rm ./content/news/2020-11-03-bevy-0.3/ecs_get_component-inverted.svg
rm ./content/news/2020-11-03-bevy-0.3/ecs_simple_insert-inverted.svg
rm ./content/news/2020-12-19-bevy-0.4/bevy_round1_dynamic-inverted.svg
rm ./content/news/2020-12-19-bevy-0.4/bevy_round1_static-inverted.svg
rm ./content/news/2020-12-19-bevy-0.4/fast_compiles-inverted.svg
rm ./content/news/2020-12-19-bevy-0.4/text_rendering-inverted.svg
rm ./content/news/2021-04-06-bevy-0.5/add_remove_big-inverted.svg
rm ./content/news/2021-04-06-bevy-0.5/frag_iter-inverted.svg
rm ./content/news/2021-04-06-bevy-0.5/sparse_frag_iter-inverted.svg
rm ./content/news/2021-08-10-bevys-first-birthday/bevy_birthday-inverted.svg
rm ./content/news/2021-08-10-bevys-first-birthday/improve-inverted.svg
rm ./content/news/2021-08-10-bevys-first-birthday/milestones-inverted.svg
rm ./content/news/2021-08-10-bevys-first-birthday/next_year-inverted.svg
rm ./content/news/2021-08-10-bevys-first-birthday/numbers-inverted.svg
rm ./content/news/2021-08-10-bevys-first-birthday/proud-inverted.svg
rm ./content/news/2022-01-08-bevy-0.6/ViewFrustum-inverted.svg
rm ./content/news/2022-01-08-bevy-0.6/commands_perf-inverted.svg
rm ./content/news/2022-01-08-bevy-0.6/pipelined_rendering-inverted.svg
rm ./content/news/2022-01-08-bevy-0.6/pipelined_rendering_stages-inverted.svg
rm ./content/news/2022-01-08-bevy-0.6/render_graph-inverted.svg
rm ./content/news/2022-01-08-bevy-0.6/unpipelined_rendering-inverted.svg
rm ./content/news/2022-07-30-bevy-0.8/label_bench-inverted.svg
rm ./content/news/2022-07-30-bevy-0.8/unstable_sort-inverted.svg
rm ./content/news/2022-08-10-bevys-second-birthday/bevy_birthday-inverted.svg
rm ./content/news/2022-08-10-bevys-second-birthday/improve-inverted.svg
rm ./content/news/2022-08-10-bevys-second-birthday/milestones-inverted.svg
rm ./content/news/2022-08-10-bevys-second-birthday/next_year-inverted.svg
rm ./content/news/2022-08-10-bevys-second-birthday/numbers-inverted.svg
rm ./content/news/2022-08-10-bevys-second-birthday/proud-inverted.svg
rm ./content/news/2023-01-14-scaling-bevy-development/scaling_bevy-inverted.svg
rm ./content/news/2023-03-06-bevy-0.10/main_schedule_diagram-inverted.svg
rm ./content/news/2023-05-17-bevy-webgpu/webgpu-inverted.svg
rm ./content/news/2023-07-09-bevy-0.11/ridge-light-view-1-inverted.svg
rm ./content/news/2023-07-09-bevy-0.11/webgpu-inverted.svg
rm ./content/news/2023-08-10-bevys-third-birthday/bevy_birthday-inverted.svg
rm ./content/news/2023-08-10-bevys-third-birthday/improve-inverted.svg
rm ./content/news/2023-08-10-bevys-third-birthday/milestones-inverted.svg
rm ./content/news/2023-08-10-bevys-third-birthday/next_year-inverted.svg
rm ./content/news/2023-08-10-bevys-third-birthday/numbers-inverted.svg
rm ./content/news/2023-08-10-bevys-third-birthday/proud-inverted.svg
rm ./content/news/2023-11-04-bevy-0.12/0.12-2DMeshes-inverted.svg
rm ./content/news/2023-11-04-bevy-0.12/0.12-3DMeshes-inverted.svg
rm ./content/news/2023-11-04-bevy-0.12/BatchedUniformBuffer-inverted.svg
rm ./content/news/2023-11-04-bevy-0.12/DynamicUniformBuffer-inverted.svg
rm ./content/news/2023-11-04-bevy-0.12/RenderSets-0.11-inverted.svg
rm ./content/news/2023-11-04-bevy-0.12/RenderSets-0.12-inverted.svg
rm ./content/news/2023-11-04-bevy-0.12/StorageBuffer-inverted.svg
rm ./content/news/2024-02-17-bevy-0.13/better_batching-inverted.svg
rm ./content/news/2024-02-17-bevy-0.13/rendering-perf-graph-inverted.svg
rm ./content/news/2024-03-11-bevy-foundation/bevy_foundation-inverted.svg
rm ./static/assets/bevy_foundation-inverted.svg
rm ./static/assets/bevy_icon_dark-inverted.svg
rm ./static/assets/bevy_logo_dark-inverted.svg
rm ./static/assets/bevy_logo_docs-inverted.svg
rm ./static/assets/bevy_ui-inverted.svg
rm ./static/assets/book-inverted.svg
rm ./static/assets/discord-inverted.svg
rm ./static/assets/ecs-inverted.svg
rm ./static/assets/error_icon-inverted.svg
rm ./static/assets/feed-inverted.svg
rm ./static/assets/fonts/fira-mono-v8-latin-regular-inverted.svg
rm ./static/assets/fonts/fira-sans-v10-latin-300-inverted.svg
rm ./static/assets/fonts/fira-sans-v10-latin-500-inverted.svg
rm ./static/assets/fonts/fira-sans-v10-latin-800-inverted.svg
rm ./static/assets/fonts/fira-sans-v10-latin-italic-inverted.svg
rm ./static/assets/fonts/fira-sans-v10-latin-regular-inverted.svg
rm ./static/assets/github-inverted.svg
rm ./static/assets/github-mark-inverted.svg
rm ./static/assets/github-mark-white-inverted.svg
rm ./static/assets/github_grey-inverted.svg
rm ./static/assets/heart-inverted.svg
rm ./static/assets/hot_reloading-inverted.svg
rm ./static/assets/icon-chevron-down-inverted.svg
rm ./static/assets/icon-chevron-left-inverted.svg
rm ./static/assets/icon-chevron-right-inverted.svg
rm ./static/assets/icon-docs-dev-inverted.svg
rm ./static/assets/icon-github-inverted.svg
rm ./static/assets/icon-hamburger-inverted.svg
rm ./static/assets/icon-pencil-inverted.svg
rm ./static/assets/icon-times-inverted.svg
rm ./static/assets/itchio-textless-inverted.svg
rm ./static/assets/mastodon-logo-purple-inverted.svg
rm ./static/assets/migration-guides-inverted.svg
rm ./static/assets/opensource-inverted.svg
rm ./static/assets/pager_next-inverted.svg
rm ./static/assets/pager_previous-inverted.svg
rm ./static/assets/people-inverted.svg
rm ./static/assets/platform-icons-inverted.svg
rm ./static/assets/progressbar-inverted.svg
rm ./static/assets/q_and_a-inverted.svg
rm ./static/assets/reddit-inverted.svg
rm ./static/assets/render_graph-inverted.svg
rm ./static/assets/rust-logo-light-inverted.svg
rm ./static/assets/scene-inverted.svg
rm ./static/assets/sound-inverted.svg
rm ./static/assets/sponsor_badges/bronze-inverted.svg
rm ./static/assets/sponsor_badges/diamond-inverted.svg
rm ./static/assets/sponsor_badges/gold-inverted.svg
rm ./static/assets/sponsor_badges/patron-inverted.svg
rm ./static/assets/sponsor_badges/platinum-inverted.svg
rm ./static/assets/sponsor_badges/silver-inverted.svg
rm ./static/assets/sponsor_badges/titanium-inverted.svg
rm ./static/assets/sponsors/Foresight_Spatial_Labs-inverted.svg
rm ./static/assets/twitter-inverted.svg
rm ./static/assets/twitter_grey-inverted.svg
rm ./static/assets/whats_a_bevy-inverted.svg
rm ./static/assets/youtube-inverted.svg
rm ./static/assets/youtube_grey-inverted.svg
