python3 invert_stream.py < content/news/2020-08-10-introducing-bevy/ecs_build.svg >  content/news/2020-08-10-introducing-bevy/ecs_build-inverted.svg 
python3 invert_stream.py < content/news/2020-08-10-introducing-bevy/ecs_iter.svg >  content/news/2020-08-10-introducing-bevy/ecs_iter-inverted.svg 
python3 invert_stream.py < content/news/2020-08-19-scaling-bevy/balance-scale.svg >  content/news/2020-08-19-scaling-bevy/balance-scale-inverted.svg 
python3 invert_stream.py < content/news/2020-09-19-bevy-0.2/bevy_tasks_1.svg >  content/news/2020-09-19-bevy-0.2/bevy_tasks_1-inverted.svg 
python3 invert_stream.py < content/news/2020-09-19-bevy-0.2/bevy_tasks_2.svg >  content/news/2020-09-19-bevy-0.2/bevy_tasks_2-inverted.svg 
python3 invert_stream.py < content/news/2020-09-19-bevy-0.2/get_component.svg >  content/news/2020-09-19-bevy-0.2/get_component-inverted.svg 
python3 invert_stream.py < content/news/2020-11-03-bevy-0.3/ecs_add_remove.svg >  content/news/2020-11-03-bevy-0.3/ecs_add_remove-inverted.svg 
python3 invert_stream.py < content/news/2020-11-03-bevy-0.3/ecs_frag_iter.svg >  content/news/2020-11-03-bevy-0.3/ecs_frag_iter-inverted.svg 
python3 invert_stream.py < content/news/2020-11-03-bevy-0.3/ecs_get_component.svg >  content/news/2020-11-03-bevy-0.3/ecs_get_component-inverted.svg 
python3 invert_stream.py < content/news/2020-11-03-bevy-0.3/ecs_simple_insert.svg >  content/news/2020-11-03-bevy-0.3/ecs_simple_insert-inverted.svg 
python3 invert_stream.py < content/news/2020-12-19-bevy-0.4/bevy_round1_dynamic.svg >  content/news/2020-12-19-bevy-0.4/bevy_round1_dynamic-inverted.svg 
python3 invert_stream.py < content/news/2020-12-19-bevy-0.4/bevy_round1_static.svg >  content/news/2020-12-19-bevy-0.4/bevy_round1_static-inverted.svg 
python3 invert_stream.py < content/news/2020-12-19-bevy-0.4/fast_compiles.svg >  content/news/2020-12-19-bevy-0.4/fast_compiles-inverted.svg 
python3 invert_stream.py < content/news/2020-12-19-bevy-0.4/text_rendering.svg >  content/news/2020-12-19-bevy-0.4/text_rendering-inverted.svg 
python3 invert_stream.py < content/news/2021-04-06-bevy-0.5/add_remove_big.svg >  content/news/2021-04-06-bevy-0.5/add_remove_big-inverted.svg 
python3 invert_stream.py < content/news/2021-04-06-bevy-0.5/frag_iter.svg >  content/news/2021-04-06-bevy-0.5/frag_iter-inverted.svg 
python3 invert_stream.py < content/news/2021-04-06-bevy-0.5/sparse_frag_iter.svg >  content/news/2021-04-06-bevy-0.5/sparse_frag_iter-inverted.svg 
python3 invert_stream.py < content/news/2021-08-10-bevys-first-birthday/bevy_birthday.svg >  content/news/2021-08-10-bevys-first-birthday/bevy_birthday-inverted.svg 
python3 invert_stream.py < content/news/2021-08-10-bevys-first-birthday/improve.svg >  content/news/2021-08-10-bevys-first-birthday/improve-inverted.svg 
python3 invert_stream.py < content/news/2021-08-10-bevys-first-birthday/milestones.svg >  content/news/2021-08-10-bevys-first-birthday/milestones-inverted.svg 
python3 invert_stream.py < content/news/2021-08-10-bevys-first-birthday/next_year.svg >  content/news/2021-08-10-bevys-first-birthday/next_year-inverted.svg 
python3 invert_stream.py < content/news/2021-08-10-bevys-first-birthday/numbers.svg >  content/news/2021-08-10-bevys-first-birthday/numbers-inverted.svg 
python3 invert_stream.py < content/news/2021-08-10-bevys-first-birthday/proud.svg >  content/news/2021-08-10-bevys-first-birthday/proud-inverted.svg 
python3 invert_stream.py < content/news/2022-01-08-bevy-0.6/ViewFrustum.svg >  content/news/2022-01-08-bevy-0.6/ViewFrustum-inverted.svg 
python3 invert_stream.py < content/news/2022-01-08-bevy-0.6/commands_perf.svg >  content/news/2022-01-08-bevy-0.6/commands_perf-inverted.svg 
python3 invert_stream.py < content/news/2022-01-08-bevy-0.6/pipelined_rendering.svg >  content/news/2022-01-08-bevy-0.6/pipelined_rendering-inverted.svg 
python3 invert_stream.py < content/news/2022-01-08-bevy-0.6/pipelined_rendering_stages.svg >  content/news/2022-01-08-bevy-0.6/pipelined_rendering_stages-inverted.svg 
python3 invert_stream.py < content/news/2022-01-08-bevy-0.6/render_graph.svg >  content/news/2022-01-08-bevy-0.6/render_graph-inverted.svg 
python3 invert_stream.py < content/news/2022-01-08-bevy-0.6/unpipelined_rendering.svg >  content/news/2022-01-08-bevy-0.6/unpipelined_rendering-inverted.svg 
python3 invert_stream.py < content/news/2022-07-30-bevy-0.8/label_bench.svg >  content/news/2022-07-30-bevy-0.8/label_bench-inverted.svg 
python3 invert_stream.py < content/news/2022-07-30-bevy-0.8/unstable_sort.svg >  content/news/2022-07-30-bevy-0.8/unstable_sort-inverted.svg 
python3 invert_stream.py < content/news/2022-08-10-bevys-second-birthday/bevy_birthday.svg >  content/news/2022-08-10-bevys-second-birthday/bevy_birthday-inverted.svg 
python3 invert_stream.py < content/news/2022-08-10-bevys-second-birthday/improve.svg >  content/news/2022-08-10-bevys-second-birthday/improve-inverted.svg 
python3 invert_stream.py < content/news/2022-08-10-bevys-second-birthday/milestones.svg >  content/news/2022-08-10-bevys-second-birthday/milestones-inverted.svg 
python3 invert_stream.py < content/news/2022-08-10-bevys-second-birthday/next_year.svg >  content/news/2022-08-10-bevys-second-birthday/next_year-inverted.svg 
python3 invert_stream.py < content/news/2022-08-10-bevys-second-birthday/numbers.svg >  content/news/2022-08-10-bevys-second-birthday/numbers-inverted.svg 
python3 invert_stream.py < content/news/2022-08-10-bevys-second-birthday/proud.svg >  content/news/2022-08-10-bevys-second-birthday/proud-inverted.svg 
python3 invert_stream.py < content/news/2023-01-14-scaling-bevy-development/scaling_bevy.svg >  content/news/2023-01-14-scaling-bevy-development/scaling_bevy-inverted.svg 
python3 invert_stream.py < content/news/2023-03-06-bevy-0.10/main_schedule_diagram.svg >  content/news/2023-03-06-bevy-0.10/main_schedule_diagram-inverted.svg 
python3 invert_stream.py < content/news/2023-05-17-bevy-webgpu/webgpu.svg >  content/news/2023-05-17-bevy-webgpu/webgpu-inverted.svg 
python3 invert_stream.py < content/news/2023-07-09-bevy-0.11/ridge-light-view-1.svg >  content/news/2023-07-09-bevy-0.11/ridge-light-view-1-inverted.svg 
python3 invert_stream.py < content/news/2023-07-09-bevy-0.11/webgpu.svg >  content/news/2023-07-09-bevy-0.11/webgpu-inverted.svg 
python3 invert_stream.py < content/news/2023-08-10-bevys-third-birthday/bevy_birthday.svg >  content/news/2023-08-10-bevys-third-birthday/bevy_birthday-inverted.svg 
python3 invert_stream.py < content/news/2023-08-10-bevys-third-birthday/improve.svg >  content/news/2023-08-10-bevys-third-birthday/improve-inverted.svg 
python3 invert_stream.py < content/news/2023-08-10-bevys-third-birthday/milestones.svg >  content/news/2023-08-10-bevys-third-birthday/milestones-inverted.svg 
python3 invert_stream.py < content/news/2023-08-10-bevys-third-birthday/next_year.svg >  content/news/2023-08-10-bevys-third-birthday/next_year-inverted.svg 
python3 invert_stream.py < content/news/2023-08-10-bevys-third-birthday/numbers.svg >  content/news/2023-08-10-bevys-third-birthday/numbers-inverted.svg 
python3 invert_stream.py < content/news/2023-08-10-bevys-third-birthday/proud.svg >  content/news/2023-08-10-bevys-third-birthday/proud-inverted.svg 
python3 invert_stream.py < content/news/2023-11-04-bevy-0.12/0.12-2DMeshes.svg >  content/news/2023-11-04-bevy-0.12/0.12-2DMeshes-inverted.svg 
python3 invert_stream.py < content/news/2023-11-04-bevy-0.12/0.12-3DMeshes.svg >  content/news/2023-11-04-bevy-0.12/0.12-3DMeshes-inverted.svg 
python3 invert_stream.py < content/news/2023-11-04-bevy-0.12/BatchedUniformBuffer.svg >  content/news/2023-11-04-bevy-0.12/BatchedUniformBuffer-inverted.svg 
python3 invert_stream.py < content/news/2023-11-04-bevy-0.12/DynamicUniformBuffer.svg >  content/news/2023-11-04-bevy-0.12/DynamicUniformBuffer-inverted.svg 
python3 invert_stream.py < content/news/2023-11-04-bevy-0.12/RenderSets-0.11.svg >  content/news/2023-11-04-bevy-0.12/RenderSets-0.11-inverted.svg 
python3 invert_stream.py < content/news/2023-11-04-bevy-0.12/RenderSets-0.12.svg >  content/news/2023-11-04-bevy-0.12/RenderSets-0.12-inverted.svg 
python3 invert_stream.py < content/news/2023-11-04-bevy-0.12/StorageBuffer.svg >  content/news/2023-11-04-bevy-0.12/StorageBuffer-inverted.svg 
python3 invert_stream.py < content/news/2024-02-17-bevy-0.13/better_batching.svg >  content/news/2024-02-17-bevy-0.13/better_batching-inverted.svg 
python3 invert_stream.py < content/news/2024-02-17-bevy-0.13/rendering-perf-graph.svg >  content/news/2024-02-17-bevy-0.13/rendering-perf-graph-inverted.svg 
python3 invert_stream.py < content/news/2024-03-11-bevy-foundation/bevy_foundation.svg >  content/news/2024-03-11-bevy-foundation/bevy_foundation-inverted.svg 
python3 invert_stream.py < static/assets/bevy_foundation.svg >  static/assets/bevy_foundation-inverted.svg 
python3 invert_stream.py < static/assets/bevy_icon_dark.svg >  static/assets/bevy_icon_dark-inverted.svg 
python3 invert_stream.py < static/assets/bevy_logo_dark.svg >  static/assets/bevy_logo_dark-inverted.svg 
python3 invert_stream.py < static/assets/bevy_logo_docs.svg >  static/assets/bevy_logo_docs-inverted.svg 
python3 invert_stream.py < static/assets/bevy_ui.svg >  static/assets/bevy_ui.svg 
python3 invert_stream.py < static/assets/book.svg >  static/assets/book-inverted.svg 
python3 invert_stream.py < static/assets/discord.svg >  static/assets/discord-inverted.svg 
python3 invert_stream.py < static/assets/ecs.svg >  static/assets/ecs-inverted.svg 
python3 invert_stream.py < static/assets/error_icon.svg >  static/assets/error_icon-inverted.svg 
python3 invert_stream.py < static/assets/feed.svg >  static/assets/feed-inverted.svg 
python3 invert_stream.py < static/assets/fonts/fira-mono-v8-latin-regular.svg >  static/assets/fonts/fira-mono-v8-latin-regular-inverted.svg 
python3 invert_stream.py < static/assets/fonts/fira-sans-v10-latin-300.svg >  static/assets/fonts/fira-sans-v10-latin-300-inverted.svg 
python3 invert_stream.py < static/assets/fonts/fira-sans-v10-latin-500.svg >  static/assets/fonts/fira-sans-v10-latin-500-inverted.svg 
python3 invert_stream.py < static/assets/fonts/fira-sans-v10-latin-800.svg >  static/assets/fonts/fira-sans-v10-latin-800-inverted.svg 
python3 invert_stream.py < static/assets/fonts/fira-sans-v10-latin-italic.svg >  static/assets/fonts/fira-sans-v10-latin-italic-inverted.svg 
python3 invert_stream.py < static/assets/fonts/fira-sans-v10-latin-regular.svg >  static/assets/fonts/fira-sans-v10-latin-regular-inverted.svg 
python3 invert_stream.py < static/assets/github-mark-white.svg >  static/assets/github-mark-white-inverted.svg 
python3 invert_stream.py < static/assets/github-mark.svg >  static/assets/github-mark-inverted.svg 
python3 invert_stream.py < static/assets/github.svg >  static/assets/github.svg 
python3 invert_stream.py < static/assets/github_grey.svg >  static/assets/github_grey-inverted.svg 
python3 invert_stream.py < static/assets/heart.svg >  static/assets/heart.svg 
python3 invert_stream.py < static/assets/hot_reloading.svg >  static/assets/hot_reloading-inverted.svg 
python3 invert_stream.py < static/assets/icon-chevron-down.svg >  static/assets/icon-chevron-down-inverted.svg 
python3 invert_stream.py < static/assets/icon-chevron-left.svg >  static/assets/icon-chevron-left-inverted.svg 
python3 invert_stream.py < static/assets/icon-chevron-right.svg >  static/assets/icon-chevron-right-inverted.svg 
python3 invert_stream.py < static/assets/icon-docs-dev.svg >  static/assets/icon-docs-dev-inverted.svg 
python3 invert_stream.py < static/assets/icon-github.svg >  static/assets/icon-github-inverted.svg 
python3 invert_stream.py < static/assets/icon-hamburger.svg >  static/assets/icon-hamburger-inverted.svg 
python3 invert_stream.py < static/assets/icon-pencil.svg >  static/assets/icon-pencil-inverted.svg 
python3 invert_stream.py < static/assets/icon-times.svg >  static/assets/icon-times.svg 
python3 invert_stream.py < static/assets/itchio-textless.svg >  static/assets/itchio-textless-inverted.svg 
python3 invert_stream.py < static/assets/mastodon-logo-purple.svg >  static/assets/mastodon-logo-purple-inverted.svg 
python3 invert_stream.py < static/assets/migration-guides.svg >  static/assets/migration-guides-inverted.svg 
python3 invert_stream.py < static/assets/opensource.svg >  static/assets/opensource.svg 
python3 invert_stream.py < static/assets/pager_next.svg >  static/assets/pager_next-inverted.svg 
python3 invert_stream.py < static/assets/pager_previous.svg >  static/assets/pager_previous-inverted.svg 
python3 invert_stream.py < static/assets/people.svg >  static/assets/people.svg 
python3 invert_stream.py < static/assets/platform-icons.svg >  static/assets/platform-icons-inverted.svg 
python3 invert_stream.py < static/assets/progressbar.svg >  static/assets/progressbar-inverted.svg 
python3 invert_stream.py < static/assets/q_and_a.svg >  static/assets/q_and_a.svg 
python3 invert_stream.py < static/assets/reddit.svg >  static/assets/reddit-inverted.svg 
python3 invert_stream.py < static/assets/render_graph.svg >  static/assets/render_graph-inverted.svg 
python3 invert_stream.py < static/assets/rust-logo-light.svg >  static/assets/rust-logo-light-inverted.svg 
python3 invert_stream.py < static/assets/scene.svg >  static/assets/scene.svg 
python3 invert_stream.py < static/assets/sound.svg >  static/assets/sound-inverted.svg 
python3 invert_stream.py < static/assets/sponsor_badges/bronze.svg >  static/assets/sponsor_badges/bronze-inverted.svg 
python3 invert_stream.py < static/assets/sponsor_badges/diamond.svg >  static/assets/sponsor_badges/diamond-inverted.svg 
python3 invert_stream.py < static/assets/sponsor_badges/gold.svg >  static/assets/sponsor_badges/gold-inverted.svg 
python3 invert_stream.py < static/assets/sponsor_badges/patron.svg >  static/assets/sponsor_badges/patron-inverted.svg 
python3 invert_stream.py < static/assets/sponsor_badges/platinum.svg >  static/assets/sponsor_badges/platinum-inverted.svg 
python3 invert_stream.py < static/assets/sponsor_badges/silver.svg >  static/assets/sponsor_badges/silver-inverted.svg 
python3 invert_stream.py < static/assets/sponsor_badges/titanium.svg >  static/assets/sponsor_badges/titanium-inverted.svg 
python3 invert_stream.py < static/assets/sponsors/Foresight_Spatial_Labs.svg >  static/assets/sponsors/Foresight_Spatial_Labs-inverted.svg 
python3 invert_stream.py < static/assets/twitter.svg >  static/assets/twitter.svg 
python3 invert_stream.py < static/assets/twitter_grey.svg >  static/assets/twitter_grey-inverted.svg 
python3 invert_stream.py < static/assets/whats_a_bevy.svg >  static/assets/whats_a_bevy-inverted.svg 
python3 invert_stream.py < static/assets/youtube.svg >  static/assets/youtube.svg 
python3 invert_stream.py < static/assets/youtube_grey.svg >  static/assets/youtube_grey-inverted.svg 
