[[sponsor]]
name = "Dead Money"
image = "dead_money.png"
link = "https://deadmoney.gg/"
amount = 250
source = "stripe"

[[sponsor]]
name = "Ida \"Iyes\""
amount = 25
source = "stripe"

[[sponsor]]
name = "abledbody"
link = "https://github.com/abledbody"
amount = 100
source = "stripe"

[[sponsor]]
name = "John Hainline"
amount = 25
source = "stripe"

[[sponsor]]
name = "HAL 9000"
amount = 50
source = "stripe"

[[sponsor]]
name = "Aevyrie Roessler"
amount = 25
source = "stripe"

[[sponsor]]
name = "Afonso Lage"
amount = 25
source = "stripe"

[[sponsor]]
name = "well, now I have to make a game in Bevy"
amount = 25
source = "stripe"

[[sponsor]]
name = "occuros"
amount = 25
source = "stripe"

[[sponsor]]
name = "nezuo"
amount = 25
source = "stripe"