# Note: these should be listed in order from lowest to highest

[[tier]]
name = "Bronze"
amount = 5
sponsor_tier = false
icon = "/assets/sponsor_badges/bronze.svg"
donate_link = "https://buy.stripe.com/5kA7vS7tPeXJ38A7ss"

[[tier]]
name = "Silver"
amount = 10
sponsor_tier = false
icon = "/assets/sponsor_badges/silver.svg"
donate_link = "https://buy.stripe.com/9AQ5nK01neXJ4cE001"

[[tier]]
name = "Gold"
amount = 25
sponsor_tier = false
icon = "/assets/sponsor_badges/gold.svg"
donate_link = "https://buy.stripe.com/9AQ5nKaG1cPB5gI28a"
reward_name = true

[[tier]]
name = "Platinum"
amount = 50
sponsor_tier = false
icon = "/assets/sponsor_badges/platinum.svg"
donate_link = "https://buy.stripe.com/eVa3fC4hD2aX7oQeUX"
reward_name = true

[[tier]]
name = "Titanium"
amount = 100
sponsor_tier = false
icon = "/assets/sponsor_badges/titanium.svg"
donate_link = "https://buy.stripe.com/5kAbM8cO9g1NfVm004"
reward_name = true
reward_link = true

[[tier]]
name = "Diamond"
amount = 250
sponsor_tier = false
icon = "/assets/sponsor_badges/diamond.svg"
donate_link = "https://buy.stripe.com/6oEaI49BX16T9wY4gl"
reward_logo = true
reward_link = true
logo_height = 45

[[tier]]
name = "Corporate Bronze"
amount = 500
sponsor_tier = true
icon = "/assets/sponsor_badges/bronze.svg"
donate_link = "https://buy.stripe.com/bIY7vSeWhaHt7oQ7sy"
reward_logo = true
reward_link = true
logo_height = 70

[[tier]]
name = "Corporate Silver"
amount = 1000
sponsor_tier = true
icon = "/assets/sponsor_badges/silver.svg"
donate_link = "https://buy.stripe.com/14kcQceWh8zleRi4gn"
reward_logo = true
reward_link = true
logo_height = 85

[[tier]]
name = "Corporate Gold"
amount = 2000
sponsor_tier = true
icon = "/assets/sponsor_badges/gold.svg"
donate_link = "https://buy.stripe.com/fZecQcdSd6rd4cEfZ6"
reward_logo = true
reward_link = true
logo_height = 90

[[tier]]
name = "Corporate Platinum"
amount = 4000
sponsor_tier = true
icon = "/assets/sponsor_badges/platinum.svg"
donate_link = "https://buy.stripe.com/fZe03q29vdTFgZq6ox"
reward_logo = true
reward_link = true
logo_height = 95

[[tier]]
name = "Corporate Titanium"
amount = 6000
sponsor_tier = true
icon = "/assets/sponsor_badges/titanium.svg"
donate_link = "https://buy.stripe.com/bIY03qaG1eXJ8sU8wG"
reward_logo = true
reward_link = true
logo_height = 100

[[tier]]
name = "Corporate Diamond"
amount = 8000
sponsor_tier = true
icon = "/assets/sponsor_badges/diamond.svg"
donate_link = "https://buy.stripe.com/00gdUg4hD6rddNe7sD"
reward_logo = true
reward_link = true
logo_height = 120

[[tier]]
name = "Patron"
amount = 13000
sponsor_tier = true
icon = "/assets/sponsor_badges/patron.svg"
donate_link = "mailto:bevyengine@gmail.com"
reward_logo = true
reward_link = true
logo_height = 190
