# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on pushes to master
#  or any pull request or pull request
on:
  push:
    branches: [master]
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master' # Only on PRs, see also build_and_deploy below
    steps:
      - uses: actions/checkout@v2

      - name: "Build website"
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          BUILD_ONLY: true
          TOKEN: fake-secret

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev

      - name: Build & run tests
        run: cd book-validation && cargo test

  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Only on a push to the master branch (like when PR's are merged)
    steps:
      - uses: actions/checkout@master

      - name: "Build and deploy website"
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          TOKEN: ${{ secrets.CART_PAT }}
